- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Allow overriding tag creation. Provide access to explicit next tag.

- timber-lint/src/main/java/timber/lint/IssueRegistry.java
- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Add lint check for tag length

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Add hook for controlling logs by priority.

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Add forest copy getter for all planted trees.

- timber-lint/build.gradle
> Build lint jar targetting Java 7 VMs.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Allow any type into a '%s' format marker.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Fix TagLength lint check to only highlight argument

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Generic log methods that allow passing a priority.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
Followed the suggestion from #86, seems to be the right fix. Still working on the lint unit test bits - hoping to have something in the next few days.
> Only emit BinaryOperation error if the operation results in a String type

- timber/src/main/java/timber/log/Timber.java
Removes 2 methods to 106 from 108.
> Remove creation of synthetic accessor methods.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Fix lint warning for tag call

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Add more strict pattern match for StringFormatInTimber

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Add Timber.plant(Tree... trees) method to plant multiple trees

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
Allows Tree to override this implementation with custom tags and argument handling.
> Log message formatting available by protected method.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Fix linter crash

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
This diff fixes the unexpected failure int the lint rules. 
https://github.com/JakeWharton/timber/issues/163
> Fix class cast exception due to too eager typing.

- timber/src/main/java/timber/log/Timber.java
Replace with android.text.TextUtils 
```
/**
* Returns true if the string is null or 0-length.
* @param str the string to be examined
* @return true if str is null or zero length
*/
public static boolean isEmpty(@Nullable CharSequence str) {
if (str == null || str.length() == 0)
return true;
else
return false;
}
```
> Simple implementation

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Migrate LogNotTimber lint check from class to source scan

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Limit underline for LogNotTimber

- build.gradle
- timber-lint/build.gradle
- timber-lint/src/main/java/timber/lint/IssueRegistry.java
- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
> Add unit tests for custom Lint checks

- build.gradle
- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
> Port lint checks from Lombok to PSI

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
> Fix NPE when String.format inside block or nested assignment

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
Closes #199
The wordings could be improved also I wasn't sure which severity and importance to give to the Lint Check.
> Add Timber Lint Check for exception logging

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Truncate auto-generated log tags over 23 characters

- build.gradle
- timber-lint/build.gradle
- timber-sample/build.gradle
- timber/build.gradle
> Clean up versions and deps

- build.gradle
- timber-lint/build.gradle
- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
- timber/build.gradle
* Replace lintrules plugin with [built-in lint configuration](https://github.com/tnorbye/android-custom-lint-rules/blob/e01536a9676fa5e2ac13d5315c71688a9b38314b/android-studio-3/README.md#lint-check-aar-library)
* Update to [new Lint Registry](https://github.com/googlesamples/android-custom-lint-rules/blob/master/android-studio-3/checks/build.gradle#L17,L19) for UAST support
* Port lint checks to [UAST](https://groups.google.com/d/msg/lint-dev/7nLiXa04baM/TuceBxWXAQAJ)
* Migrate lint tests to new TestLintTask style
Fixes #242
> Migrate lint checks to UAST

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
> Limit ISSUE_LOG check to API <= 23

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Only truncate log tag to 23 on API 23 and earlier.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
- timber-sample/src/main/java/com/example/timber/ui/LintActivity.java
> Supply quickfixes for lint checks

- build.gradle
- timber-sample/src/main/java/com/example/timber/ui/LintActivity.java
Also, update comment in LintActivity now that
https://issuetracker.google.com/issues/65941946 is fixed.
> Bump AGP to 3.0.0-rc1

- build.gradle
- timber-sample/src/main/java/com/example/timber/ExampleApp.java
- timber/build.gradle
- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
> Add nullability annotations.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
> Fix lint npe static string format

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
> Don't check non-constant fields as arguments for null

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
- timber-sample/src/main/java/com/example/timber/ui/LintActivity.java
> Include single-arg exception log methods in TimberExceptionLogging check

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
> Fix false positives when evaluating parameters and methods

- timber/src/main/java/timber/log/Timber.java
Replaced for loops with for each for better performance and code readability.
> Performance enhancements and better code readability.

- build.gradle
...and some other dependencies
> Bump to AGP 3.1 Final

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
This fixes a lint crash when a selector other than `UCallExpression` is present.
> Only evaluate UCallExpression for getMessage checks

- timber/src/main/java/timber/log/Timber.kt
Java callers go through a JvmStatic trampoline whereas Kotlin callers go directly to the companion. Additionally, R8 and ProGuard can remove some of these frames causing problems. Instead of trying to be clever with indices, skip frames which are in known library types.
> Use variable-sized stack frame skipping

- timber/build.gradle
- timber/src/main/java/timber/log/Timber.kt
Other small API tweaks for Kotlin.
> Make companion directly a Tree

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
> Allow long in date formatting args

- timber/src/main/java/timber/log/Timber.kt
Param message is not nullable.
> Fix Tree.log doc

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
> Allow string literal concatenation

- build.gradle
- gradle.properties
- timber-sample/build.gradle
- timber-sample/src/main/java/com/example/timber/ExampleApp.java
- timber-sample/src/main/java/com/example/timber/ui/DemoActivity.java
- timber-sample/src/main/java/com/example/timber/ui/LintActivity.java
> Remove ButterKnife

- timber-lint/build.gradle
- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
- The tag length check was looking at minSdk <= 23 but the docs say that it applies until API 26
- https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)
Closes #426
> Fix some issues with the lint detector
