- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
This allows planting the tree for the tag behavior but redirecting the logs elsewhere. This also forbids extending the actual logging methods on this tree.
> Provide a callback for logging a message on a DebugTree.

- pom.xml
- timber-lint/pom.xml
- timber-sample/pom.xml
- timber-sample/src/main/java/com/example/timber/ExampleApp.java
- timber-sample/src/main/java/com/example/timber/FakeCrashLibrary.java
- timber/pom.xml
- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
* All trees are now taggable.
* Provide a single method through which all level-specific methods log.
* Eliminate the need for HollowTree.
Closes #50. Closes #54.
> Major architectural changes... for a single-class logging library.

- timber/build.gradle
- timber/consumer-proguard-rules.pro
I upgraded to 4.0.1 and got the below Proguard warning:
```
Warning: timber.log.Timber: can't find referenced class org.jetbrains.annotations.NonNls
```
Added `-dontwarn` Proguard config for my project and thought it would help to include consumer proguard config.
> Consumer Proguard rule is added

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
The built-in method hides UnknownHostException.  This diff adds a method to get a Throwable's stack trace as a string that does not exhibit this behavior.
Fixes #87.
> Replace use of Log#getStackTraceString(Throwable)

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
Per #82 - went ahead and switched both the formatting argument and the method argument to use 1-based indexing; felt like it was more user friendly. (Can switch to 0-based indexing though, these _are_ developers after all)
```
ExampleApp.java:25: Error: Wrong argument type for formatting argument '#1' in success = %b: conversion is 'b', received String (argument #2 in method call) [TimberArgTypes]
Timber.d("success = %b", taskName);
~~~~~~~~
Explanation for issues of type "TimberArgTypes":
The argument types that you specified in your formatting string does not
match the types of the arguments that you passed to your formatting call.
```
> Switch to 1-based indexing for arg types check

- build.gradle
Dear Jake Wharton, limiting minSdkVersion to 15 is a big drawback for me using Timber as a useful dependency in my Applications. I change it to 9 and nothing goes wrong, please solve this issue by this pull request.
> change minSdkVersion to 9

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
Refactors Timber's main `String.format` argument linting to be re-usable by new
fuzzy check added to detect `Timber.tag().v`-pattern log calls; eg:
```java
Timber.v(...); // Before this commit: correctly linting the elipses
tree = Timber.tag().v(
"digit: '%d'\n",
"BUG HERE: tree logs ignored; fixed in this commit!");
// After this commit: ^this incorrect `%d` usage is caught, as expected
```
`v` here is an example - actually re-uses same list of log method-checking
elsewhere in the code
> bug fix: make Timber lint run on Timber.tag() logs

- timber/src/test/java/timber/log/TimberTest.java
Going by the name of the test and the presence of the CountdownLatch its obvious the intent was to test execution on a second thread, not direct execution through a Thread object.
> exceptionFromSpawnedThread - Actually test on a spawned thread.

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
This is a breaking API change, but we call `getTag()` before calling `isLoggable()` and it is useful for filtering.
> Add ability to filter logs by log tag.

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
This fixes the unexpected lint error, it was caused by optimistically assuming the grabbed node has arguments:
NoSuchElementException:ListAccessor$4$1.next(ListAccessor.java:525)<-ListAccessor$4$1.next(ListAccessor.java:502)<-WrongTimberUsageDetector.visitMethod(WrongTimberUsageDetector.java:116)<-JavaVisitor$DelegatingJavaVisitor.visitMethodInvocation(JavaVisitor.java:1442)
> Fix NoSuchElementException in timber lint.

- timber/src/main/java/timber/log/Timber.java
This reverts commit f10e7af1aec0e3628b5597cc8103bc5d2ea3828d.
Simply to avoid this in JUnit tests:
> java.lang.RuntimeException: Method isEmpty in android.text.TextUtils not mocked. See http://g.co/androidstudio/not-mocked for details.
> Revert "Simple implementation"

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
This will avoid false positive on dates.
Date format token always start with a `t`/`T` and is followed by a char that will specify the actual format [1].
[1] https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html
> Fix lint warning with dates

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
Lint was failing for `%b` format with `Boolean` value. This fixes that issue.
> Handle wrapped boolean in lint

- build.gradle
The Timber lint checks fail when run on projects using the Android Gradle Plugin version 2.3.0 due to breaking changes to the lint apis. Bumping this project to the latest lint tools resolves this.
> Bump lint tools to 25.3.0

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
The TimberExceptionLogging lint was overly aggressive, finding calls where an
exception is logged along with a message in a variable
This fixes the lint check and adds unit tests
> Fix lint warning on d(ex, msg)

- build.gradle
- checkstyle.xml
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- timber-lint/build.gradle
- timber-sample/build.gradle
- timber/build.gradle
- timber/src/test/java/timber/log/TimberTest.java
* New dependency configuration syntax
* Add Google Maven repository to allprojects.repositories
* Bump Gradle to 4.1-rc-1
* As of Gradle 3.5-rc-1, the default version of checkstyle is bumped from version 5.9 to 6.19 which removes the RedundantThrows check. 
See https://github.com/gradle/gradle/commit/12cbf9734b5ea40aadf2a93aecffdbe7d1a959d8 and https://github.com/checkstyle/checkstyle/issues/473.
* As of Gradle 3.4-rc-1, the exceptions created in the unit tests now have a longer
stack trace due to https://github.com/gradle/gradle/commit/23920dc74bed318ad5238dcd30f3349a606001a3.
The longer trace passes the Timber.MAX_LOG_LENGTH threshold and is
split into lines ultimately failing assertions over log size.  This commit includes a fix for this by truncating the stack traces of the created …
> Upgrade to Android Gradle Plugin 3.0.0-alpha8

- timber-sample/src/main/java/com/example/timber/ui/LintActivity.java
Lint failures should display in the IDE again once the fix discussed here
is released: https://issuetracker.google.com/issues/62914381#comment10
This commit showcases the current suite of checks with some failure
examples.
> Add Timber lint failure examples

- timber-lint/build.gradle
- timber-sample/build.gradle
* Update lint dependencies to 'compileOnly' configuration
* Update custom lint checks to run on :timber-sample
See https://issuetracker.google.com/issues/62914381#comment23
> Fix custom lint checks

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
UCallExpression.getMethodName() returns null when the expression is a
JavaConstructorUCallExpression.
Fixes #256
> Fix lint NPE

- timber/src/main/java/timber/log/Timber.java
- timber/src/test/java/timber/log/TimberTest.java
It's possible that an optimization elides the empty array and chooses to pass null.
Closes #239.
> Handle a null args Object[].

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.java
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.java
Cleanup of #278; the underlying issue is that there are many types of UCallExpression, but this check only cares about explicit method calls.
> Fix nested String.format check

- timber/build.gradle
We can't assume that dependent projects will have jetbrains annotations
in the classpath.
This is causing problems like #295.
> Change annotations from a compileOnly to an implementation dependency.

- timber/src/test/java/timber/log/TimberTest.java
The ignored test in `TimberTest` was failing because `Log.isLoggable()` returns false for all priorities less than `INFO`. I just changed the test to use `Timber.i()` instead of `Timber.d()`.
> Fix ignored test by using INFO log instead of DEBUG log

- build.gradle
- timber-sample/build.gradle
- timber/build.gradle
With AGP 3.4.0, libraries that publish their lint checks have to use the newer `lintPublish` API.
> Move to newer lintPublish API

- build.gradle
Hey @JakeWharton looks like the Timber repo is pretty static, but this is a quick jetbrains-annotations dependency bump that passes `./gradlew clean test` in my fork anyway
I suppose if nothing merges + releases here I can just exclude jetbrains-annotations from my timber dep so it doesn't transitively constrain me from updating the dep since it appears to work fine
Cheers
Fixes #391
> Update jetbrains-annotations dependency to current

- CHANGELOG.md
- timber/src/main/java/timber/log/Timber.kt
- timber/src/test/java/timber/log/TimberTest.kt
- https://issuetracker.google.com/issues/124593220
The lint check is fixed by https://github.com/JakeWharton/timber/pull/421/
> Tag length limit was removed in API 26 not API 24

- timber-lint/src/main/java/timber/lint/WrongTimberUsageDetector.kt
- timber-lint/src/test/java/timber/lint/WrongTimberUsageDetectorTest.kt
- timber-sample/src/main/java/com/example/timber/ui/JavaLintActivity.java
- timber-sample/src/main/java/com/example/timber/ui/KotlinLintActivity.kt
Stacked on https://github.com/JakeWharton/timber/pull/431
cc: @tnorbye
Closes https://github.com/JakeWharton/timber/pull/401.  Closes https://github.com/JakeWharton/timber/pull/317.
> Update Lint checks for Kotlin consumers
